# continue-config.yml
version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-deploy-server:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare environment
          command: |
            cd server
            cp .env.example .env
      - docker/build:
          image: rekkoo-server
          path: ./server
      - run:
          name: Save Docker image
          command: |
            docker save rekkoo-server:latest | gzip > rekkoo-server.tar.gz
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Deploy to Hetzner VPS
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts 2>/dev/null
            
            echo "Copying files..."
            scp rekkoo-server.tar.gz ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/server/
            scp server/.env ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/server/
            scp server/docker-compose.yml ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/server/
            
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} \
              "cd /home/rekkoo/server && \
              docker load < rekkoo-server.tar.gz && \
              docker-compose down && \
              docker-compose up -d && \
              rm rekkoo-server.tar.gz"
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

  build-and-deploy-web-portal:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare environment
          command: |
            cd web-portal
            cp .env.example .env
      - docker/build:
          image: rekkoo-web-portal
          path: ./web-portal
      - run:
          name: Save Docker image
          command: |
            docker save rekkoo-web-portal:latest | gzip > rekkoo-web-portal.tar.gz
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Deploy to Hetzner VPS
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts 2>/dev/null
            
            echo "Copying files..."
            scp rekkoo-web-portal.tar.gz ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/web-portal/
            scp web-portal/.env ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/web-portal/
            scp web-portal
