version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

jobs:
  build-and-test-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            npm install
      - run:
          name: Run Web Portal Tests
          command: |
            cd web-portal
            npm test
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - slack/notify:
          event: pass
          channel: circleci-builds
          template: basic_success_1
      - slack/notify:
          event: fail
          channel: circleci-builds
          template: basic_fail_1

workflows:
  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-test-web-portal:
          context: slack-secrets
