# continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-deploy-server:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Build Server
          command: |
            cd server
            npm run build
      - run:
          name: Deploy to Hetzner VPS
          command: |
            # Add Hetzner VPS to known hosts
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts
            # Create deployment directory if it doesn't exist
            ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "mkdir -p ~/deployments/server"
            # Copy build files to server
            scp -r server/dist/* ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:~/deployments/server/
            # Restart application (adjust command based on your setup)
            # ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "cd ~/deployments/server && pm2 restart server || pm2 start dist/index.js --name server"
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

  build-and-deploy-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            npm install
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - run:
          name: Deploy to Hetzner VPS
          command: |
            # Add Hetzner VPS to known hosts
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts
            # Create deployment directory if it doesn't exist
            ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "mkdir -p ~/deployments/web-portal"
            # Copy build files to server
            scp -r web-portal/dist/* ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:~/deployments/web-portal/
            # Restart nginx if needed
            # ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "sudo systemctl reload nginx"
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

workflows:
  version: 2
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-deploy-server:
          context:
            - slack-secrets
            - hetzner-deploy-secrets

  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-deploy-web-portal:
          context:
            - slack-secrets
            - hetzner-deploy-secrets
