# .circleci/continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            npm install
      - run:
          name: Lint Web Portal
          command: |
            cd web-portal
            npm run lint
      - run:
          name: Run Web Portal Tests
          command: |
            cd web-portal
            npm test
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - slack/notify:
          event: pass
          channel: circleci-builds
          template: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🌐 Web Portal Build Success",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build:*\n$CIRCLE_BUILD_NUM"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nSuccess"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration:*\n$CIRCLE_JOB_DURATION"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          event: fail
          channel: circleci-builds
          template: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Web Portal Build Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build:*\n$CIRCLE_BUILD_NUM"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nFailed"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration:*\n$CIRCLE_JOB_DURATION"
                    }
                  ]
                }
              ]
            }

workflows:
  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-test-web-portal:
          context:
            - slack-secrets
