version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-server:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/server
      - run:
          name: Run Server Tests
          command: cd server && npm test
      - run:
          name: Build Server
          command: |
            cd server
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - server/dist
      - slack/notify:
          channel: circleci-builds
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Server Build & Test Successful",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n${CIRCLE_BUILD_NUM}"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          channel: circleci-builds
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Server Build & Test Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n${CIRCLE_BUILD_NUM}"
                    }
                  ]
                }
              ]
            }

  build-and-test-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/web-portal
      - run:
          name: Run Web Portal Tests
          command: cd web-portal && npm test
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - web-portal/dist
      - slack/notify:
          channel: circleci-builds
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Web Portal Build & Test Successful",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n${CIRCLE_BUILD_NUM}"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          channel: circleci-builds
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Web Portal Build & Test Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n${CIRCLE_BUILD_NUM}"
                    }
                  ]
                }
              ]
            }

workflows:
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-test-server:
          context: slack-secrets

  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-test-web-portal:
          context: slack-secrets
