# .circleci/continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-server:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Debug - List Directory Contents
          command: |
            pwd
            ls -la
            ls -la server
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/server
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Run Server Tests
          command: |
            cd server
            npm test
      - run:
          name: Build Server
          command: |
            cd server
            echo "Current directory contents:"
            ls -la
            echo "Running build..."
            npm run build
            echo "Build complete. Dist directory contents:"
            ls -la dist
      - persist_to_workspace:
          root: .
          paths:
            - server/dist
      - run:
          name: Debug - Slack Token
          command: |
            if [ -n "$SLACK_ACCESS_TOKEN" ]; then
              echo "Slack token is set"
            else
              echo "Slack token is NOT set"
            fi
      - slack/notify:
          channel: circleci-builds
          event: always
          custom: |
            {
              "text": "Server Build Status",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Server Build Status:* ${CIRCLE_JOB}\n*Branch:* ${CIRCLE_BRANCH}\n*Build:* ${CIRCLE_BUILD_NUM}"
                  }
                }
              ]
            }

workflows:
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-test-server:
          context: slack-secrets
