# .circleci/continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Debug - Check Directory Structure Before Install
          command: |
            echo "Current working directory:"
            pwd
            echo "\nRoot directory contents:"
            ls -la
            echo "\nWeb Portal directory contents:"
            ls -la web-portal/
            echo "\nPackage.json content:"
            cat web-portal/package.json
      - restore_cache:
          keys:
            - v1-web-portal-deps-{{ checksum "web-portal/package.json" }}
            - v1-web-portal-deps-
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            npm install
      - run:
          name: Lint Web Portal
          command: |
            cd web-portal
            npm run lint
      - run:
          name: Run Web Portal Tests
          command: |
            cd web-portal
            npm test
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
            echo "\nDist directory contents after build:"
            ls -la dist/
      - persist_to_workspace:
          root: .
          paths:
            - web-portal/dist
      - slack/notify:
          channel: circleci-builds
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🌐 Web Portal Build {{ job.status }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build:*\n${CIRCLE_BUILD_NUM}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n{{ job.status }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration:*\n{{ job.duration }}"
                    }
                  ]
                }
              ]
            }

workflows:
  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-test-web-portal:
          context: slack-secrets
