# continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-deploy-server:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Configure npm
          command: |
            # Use the official registry with increased timeout and retries
            npm config set registry https://registry.npmjs.org/
            npm config set fetch-retry-maxtimeout 600000
            npm config set fetch-retry-mintimeout 20000
            npm config set fetch-retries 5
            # Try alternate registry if official fails
            npm config set registry https://registry.npmmirror.com/ || npm config set registry https://registry.npmjs.org/
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            # Clear existing npm cache
            npm cache clean --force
            # Install with retries and network timeout
            npm install --network-timeout=100000 --verbose || {
              echo "First attempt failed, trying with legacy peer deps..."
              npm install --legacy-peer-deps --network-timeout=100000 --verbose
            }
      - run:
          name: Build Server
          command: |
            cd server
            npm run build
      - run:
          name: Setup SSH and Deploy to Hetzner VPS
          command: |
            # Enable SSH debugging
            set -x
            
            # Create .ssh directory and set permissions
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            
            # Clear known_hosts to avoid any stale entries
            rm -f ~/.ssh/known_hosts
            
            # Add Hetzner VPS to known hosts with strict host key checking disabled for first connection
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts 2>/dev/null
            
            # Test SSH connection first
            ssh -o "StrictHostKeyChecking=no" -o "BatchMode=yes" ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "echo 'SSH connection successful'"
            
            # If connection test passed, proceed with deployment
            echo "Creating deployment directory..."
            ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "mkdir -p ~/deployments/server"
            
            echo "Copying build files..."
            scp -r server/dist/* ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:~/deployments/server/
            
            # echo "Restarting application..."
            # ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "cd ~/deployments/server && pm2 restart server || pm2 start dist/index.js --name server"
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

  build-and-deploy-web-portal:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${HETZNER_SSH_KEY_FINGERPRINT}"
      - run:
          name: Configure npm
          command: |
            # Use the official registry with increased timeout and retries
            npm config set registry https://registry.npmjs.org/
            npm config set fetch-retry-maxtimeout 600000
            npm config set fetch-retry-mintimeout 20000
            npm config set fetch-retries 5
            # Try alternate registry if official fails
            npm config set registry https://registry.npmmirror.com/ || npm config set registry https://registry.npmjs.org/
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            # Clear existing npm cache
            npm cache clean --force
            # Install with retries and network timeout
            npm install --network-timeout=100000 --verbose || {
              echo "First attempt failed, trying with legacy peer deps..."
              npm install --legacy-peer-deps --network-timeout=100000 --verbose
            }
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - run:
          name: Setup SSH and Deploy to Hetzner VPS
          command: |
            # Enable SSH debugging
            set -x
            
            # Create .ssh directory and set permissions
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            
            # Clear known_hosts to avoid any stale entries
            rm -f ~/.ssh/known_hosts
            
            # Add Hetzner VPS to known hosts with strict host key checking disabled for first connection
            ssh-keyscan -H ${HETZNER_VPS_HOST} >> ~/.ssh/known_hosts 2>/dev/null
            
            # Test SSH connection first
            ssh -o "StrictHostKeyChecking=no" -o "BatchMode=yes" ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "echo 'SSH connection successful'"
            
            # If connection test passed, proceed with deployment
            echo "Creating deployment directory..."
            ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "mkdir -p ~/deployments/web-portal"
            
            echo "Copying build files..."
            scp -r web-portal/dist/* ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:~/deployments/web-portal/
            
            # echo "Restarting nginx..."
            # ssh ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "sudo systemctl reload nginx"
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

workflows:
  version: 2
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-deploy-server:
          context:
            - slack-secrets
            - hetzner-deploy-secrets

  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-deploy-web-portal:
          context:
            - slack-secrets
            - hetzner-deploy-secrets
