# .circleci/continue-config.yml
version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-server:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Debug - Check Directory Structure Before Install
          command: |
            echo "Current working directory:"
            pwd
            echo "\nRoot directory contents:"
            ls -la
            echo "\nServer directory contents:"
            ls -la server/
            echo "\nPackage.json content:"
            cat server/package.json
      - restore_cache:
          keys:
            - v1-server-deps-{{ checksum "server/package.json" }}
            - v1-server-deps-
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Debug - Check Node Modules After Install
          command: |
            echo "Server directory contents after install:"
            ls -la server/
            echo "\nNode modules directory:"
            ls -la server/node_modules/
            echo "\nInstalled dependencies:"
            cd server && npm list --depth=0
      - save_cache:
          paths:
            - server/node_modules
          key: v1-server-deps-{{ checksum "server/package.json" }}
      - run:
          name: Run Server Tests
          command: |
            cd server
            npm test
      - run:
          name: Build Server
          command: |
            cd server
            npm run build
            echo "\nDist directory contents after build:"
            ls -la dist/
      - persist_to_workspace:
          root: .
          paths:
            - server/dist
      - slack/notify:
          channel: circleci-builds
          event: always
          custom: |
            {
              "text": "Server Build Status",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Server Build Status:* ${CIRCLE_JOB}\n*Branch:* ${CIRCLE_BRANCH}\n*Build:* ${CIRCLE_BUILD_NUM}"
                  }
                }
              ]
            }

workflows:
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-test-server:
          context: slack-secrets
