version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

parameters:
  run-server-workflow:
    type: boolean
    default: false
  run-web-portal-workflow:
    type: boolean
    default: false

jobs:
  build-and-test-server:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Build Server
          command: |
            cd server
            npm run build
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

  build-and-test-web-portal:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Web Portal Dependencies
          command: |
            cd web-portal
            npm install
      - run:
          name: Build Web Portal
          command: |
            cd web-portal
            npm run build
      - slack/notify:
          event: always
          channel: circleci-builds
          template: basic_success_1

workflows:
  version: 2
  server-workflow:
    when: << pipeline.parameters.run-server-workflow >>
    jobs:
      - build-and-test-server:
          context: slack-secrets

  web-portal-workflow:
    when: << pipeline.parameters.run-web-portal-workflow >>
    jobs:
      - build-and-test-web-portal:
          context: slack-secrets
