# web-portal/docker-compose.yml
version: '3.8'

services:
  web-portal:
    image: rekkoo-web-portal:latest
    container_name: rekkoo-web-portal
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - TZ=UTC
    volumes:
      - ./logs:/usr/share/nginx/logs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-portal.rule=Host(`web-portal.rekkoo.com`)"
      - "traefik.http.routers.web-portal.entrypoints=websecure"
      - "traefik.http.routers.web-portal.tls=true"
      - "traefik.http.routers.web-portal.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-portal.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
