# server/docker-compose.yml
version: '3.8'

services:
  server:
    image: rekkoo-server:latest
    container_name: rekkoo-server
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`server.rekkoo.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
      - "traefik.http.services.server.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
